export type Lang='en'|'mr'|'hi';
export type Business={id:string;line:string;name:string;nameMr:string;nameHi:string;cost:number;working:number;sales:number;opex:number;skills:string[];resources:string[];signals:string[];risk:string[];support:string[];description:string;descriptionMr:string;descriptionHi:string;};
export type Location={district:string;talukas:string[];odop:string;market:number;purchasing:number;logistics:number;signals:string[]};

export const LOCATIONS:Location[]=[
 {district:'Nashik',talukas:['Nashik','Sinnar','Niphad','Dindori','Yeola'],odop:'Onion-based products',market:86,purchasing:78,logistics:84,signals:['onion','grapes','dairy','food']},
 {district:'Pune',talukas:['Pune','Baramati','Junnar','Shirur','Mulshi'],odop:'Tomato-based products',market:92,purchasing:91,logistics:91,signals:['vegetables','food','services','retail']},
 {district:'Kolhapur',talukas:['Karvir','Hatkanangale','Shirol','Kagal','Panhala'],odop:'Sugarcane / jaggery products',market:82,purchasing:79,logistics:80,signals:['dairy','sugarcane','jaggery','food']},
 {district:'Nagpur',talukas:['Nagpur','Katol','Hingna','Kamptee','Ramtek'],odop:'Mandarin orange products',market:87,purchasing:82,logistics:86,signals:['orange','food','retail','services']},
 {district:'Nandurbar',talukas:['Nandurbar','Shahada','Taloda','Akkalkuwa','Navapur'],odop:'Millet-based products',market:58,purchasing:53,logistics:55,signals:['millet','livestock','honey','services']}
];
export const LINES=[
 {id:'animal',en:'Dairy & Animal Businesses',mr:'दुग्ध व पशुपालन व्यवसाय',hi:'डेयरी और पशुपालन व्यवसाय'},
 {id:'farm',en:'Farming & Farm-Linked Businesses',mr:'शेती व शेतीशी जोडलेले व्यवसाय',hi:'खेती और खेती से जुड़े व्यवसाय'},
 {id:'food',en:'Food Processing & Local Products',mr:'अन्नप्रक्रिया व स्थानिक उत्पादने',hi:'खाद्य प्रसंस्करण और स्थानीय उत्पाद'},
 {id:'retail',en:'Rural Retail & Distribution',mr:'ग्रामीण किरकोळ विक्री व वितरण',hi:'ग्रामीण रिटेल और वितरण'},
 {id:'craft',en:'Clothing, Craft & Local Manufacturing',mr:'कपडे, हस्तकला व स्थानिक उत्पादन',hi:'कपड़ा, शिल्प और स्थानीय निर्माण'},
 {id:'service',en:'Repair, Service & Local Services',mr:'दुरुस्ती, सेवा व स्थानिक सेवा व्यवसाय',hi:'रिपेयर, सर्विस और स्थानीय सेवाएँ'}
];
const b=(x:Business)=>x;
export const BUSINESSES:Business[]=[
 b({id:'dairy_small',line:'animal',name:'Small dairy unit',nameMr:'लहान दुग्ध व्यवसाय',nameHi:'छोटी डेयरी इकाई',cost:240000,working:50000,sales:65000,opex:49000,skills:['animal care','dairy'],resources:['water','shed','feed','animals','electricity'],signals:['dairy'],risk:['feed cost','animal health','milk price'],support:['PMEGP'],description:'Sell milk locally from a small, manageable herd.',descriptionMr:'लहान आणि सांभाळता येणाऱ्या जनावरांच्या कळपातून स्थानिक पातळीवर दूध विक्री.',descriptionHi:'छोटे और संभालने योग्य पशु समूह से स्थानीय स्तर पर दूध बिक्री।'}),
 b({id:'milk_products',line:'animal',name:'Milk products',nameMr:'दूधापासून उत्पादने',nameHi:'दूध से बने उत्पाद',cost:180000,working:40000,sales:70000,opex:52000,skills:['food','dairy'],resources:['water','workspace','kitchen','storage','food_safety'],signals:['dairy','food'],risk:['shelf life','raw milk supply','food safety'],support:['PMFME','PMEGP'],description:'Make products such as paneer, curd or ghee and sell locally.',descriptionMr:'पनीर, दही किंवा तूप यांसारखी उत्पादने तयार करून स्थानिक बाजारात विक्री.',descriptionHi:'पनीर, दही या घी जैसे उत्पाद बनाकर स्थानीय बाजार में बिक्री।'}),
 b({id:'goat',line:'animal',name:'Goat rearing',nameMr:'शेळीपालन',nameHi:'बकरी पालन',cost:210000,working:45000,sales:60000,opex:41000,skills:['animal care'],resources:['shed','water','goats','fodder','vet_access'],signals:['livestock'],risk:['animal health','feed','seasonal demand'],support:['PMEGP'],description:'A smaller livestock model where land and support are suitable.',descriptionMr:'जिथे जमीन व आधार उपलब्ध आहे तिथे तुलनेने लहान पशुपालन मॉडेल.',descriptionHi:'जहाँ जमीन और सहायता उपलब्ध हो वहाँ छोटा पशुपालन मॉडल।'}),
 b({id:'nursery',line:'farm',name:'Plant nursery',nameMr:'रोपवाटिका व्यवसाय',nameHi:'पौध नर्सरी',cost:140000,working:30000,sales:55000,opex:35000,skills:['plants'],resources:['water','workspace','storage'],signals:['vegetables'],risk:['seasonality','water','local demand'],support:['PMEGP'],description:'Raise seedlings for farmers, gardens and local buyers.',descriptionMr:'शेतकरी, बागकाम व स्थानिक ग्राहकांसाठी रोपे तयार करणे.',descriptionHi:'किसानों, बागवानी और स्थानीय ग्राहकों के लिए पौधे तैयार करना।'}),
 b({id:'farm_services',line:'farm',name:'Farm service business',nameMr:'शेती सेवा व्यवसाय',nameHi:'कृषि सेवा व्यवसाय',cost:160000,working:35000,sales:60000,opex:37000,skills:['farm operations'],resources:['tools','transport'],signals:['services','vegetables'],risk:['seasonality','equipment downtime'],support:['PMEGP'],description:'Provide paid farm services such as spraying, small equipment or field support.',descriptionMr:'फवारणी, लहान उपकरणे किंवा शेतातील सहाय्य अशा सशुल्क सेवा.',descriptionHi:'स्प्रे, छोटे उपकरण या खेत सहायता जैसी भुगतान वाली सेवाएँ।'}),
 b({id:'beekeeping',line:'farm',name:'Beekeeping & honey processing',nameMr:'मधमाशीपालन व मध प्रक्रिया',nameHi:'मधुमक्खी पालन और शहद प्रसंस्करण',cost:120000,working:25000,sales:45000,opex:27000,skills:['beekeeping'],resources:['bee_boxes','protective_gear','flowering_area','storage'],signals:['honey'],risk:['weather','colony health','market access'],support:['PMEGP'],description:'Keep bee colonies and process/package honey where the local ecology supports it.',descriptionMr:'स्थानिक पर्यावरण अनुकूल असल्यास मधमाशी वसाहती सांभाळून मध प्रक्रिया व पॅकिंग.',descriptionHi:'स्थानीय पर्यावरण अनुकूल होने पर मधुमक्खी पालन और शहद पैकिंग।'}),
 b({id:'pickle',line:'food',name:'Pickle & local food unit',nameMr:'लोणची व स्थानिक खाद्यपदार्थ',nameHi:'अचार और स्थानीय खाद्य इकाई',cost:100000,working:25000,sales:45000,opex:27000,skills:['food'],resources:['kitchen','workspace','storage','packaging','food_safety'],signals:['onion','vegetables','food'],risk:['food safety','shelf life','sales consistency'],support:['PMFME','PMEGP'],description:'Small-batch local food products using locally available ingredients.',descriptionMr:'स्थानिक उपलब्ध घटक वापरून लहान प्रमाणात खाद्यपदार्थ तयार करणे.',descriptionHi:'स्थानीय सामग्री से छोटे बैच में खाद्य उत्पाद बनाना।'}),
 b({id:'flour_millet',line:'food',name:'Flour & millet products',nameMr:'पीठ व मिलेट उत्पादने',nameHi:'आटा और मिलेट उत्पाद',cost:150000,working:35000,sales:60000,opex:37000,skills:['food'],resources:['workspace','grinding_setup','packaging','storage','food_safety'],signals:['millet','jaggery','food'],risk:['raw material price','quality','market competition'],support:['PMFME','PMEGP'],description:'Process grains or millets into convenient local products.',descriptionMr:'धान्य किंवा मिलेटचे सोयीस्कर स्थानिक उत्पादनांमध्ये रूपांतर.',descriptionHi:'अनाज या मिलेट को सुविधाजनक स्थानीय उत्पादों में बदलना।'}),
 b({id:'fruit_processing',line:'food',name:'Fruit processing',nameMr:'फळ प्रक्रिया व्यवसाय',nameHi:'फल प्रसंस्करण व्यवसाय',cost:220000,working:45000,sales:75000,opex:47000,skills:['food'],resources:['workspace','processing_equipment','packaging','storage','food_safety'],signals:['grapes','orange','food'],risk:['seasonality','shelf life','raw material price'],support:['PMFME','PMEGP'],description:'Turn locally available fruit into value-added products.',descriptionMr:'स्थानिक फळांपासून मूल्यवर्धित उत्पादने तयार करणे.',descriptionHi:'स्थानीय फलों से मूल्यवर्धित उत्पाद बनाना।'}),
 b({id:'rural_retail',line:'retail',name:'Rural general retail',nameMr:'ग्रामीण जनरल रिटेल',nameHi:'ग्रामीण जनरल रिटेल',cost:180000,working:60000,sales:90000,opex:72000,skills:['retail'],resources:['shop_space','shelves','inventory_capital','supplier_linkage'],signals:['retail'],risk:['thin margins','inventory lock-in','competition'],support:['PMEGP'],description:'A local convenience shop serving everyday household needs.',descriptionMr:'दैनंदिन गरजा पूर्ण करणारे स्थानिक किरकोळ दुकान.',descriptionHi:'दैनिक घरेलू जरूरतों को पूरा करने वाली स्थानीय दुकान।'}),
 b({id:'agri_retail',line:'retail',name:'Agricultural-input retail',nameMr:'कृषी निविष्ठा दुकान',nameHi:'कृषि-इनपुट रिटेल',cost:250000,working:80000,sales:115000,opex:90000,skills:['retail','agriculture'],resources:['shop_space','shelves','inventory_capital','supplier_linkage','storage'],signals:['vegetables','millet'],risk:['inventory','seasonality','compliance'],support:['PMEGP'],description:'Sell selected farm inputs where supplier access and local demand are strong.',descriptionMr:'पुरवठादार संपर्क व स्थानिक मागणी मजबूत असल्यास निवडक कृषी निविष्ठांची विक्री.',descriptionHi:'जहाँ सप्लायर और स्थानीय मांग मजबूत हो वहाँ चुने हुए कृषि इनपुट बेचना।'}),
 b({id:'distribution',line:'retail',name:'Local produce distribution',nameMr:'स्थानिक उत्पादन वितरण',nameHi:'स्थानीय उत्पाद वितरण',cost:170000,working:50000,sales:105000,opex:84000,skills:['sales','logistics'],resources:['transport','storage','market_linkage'],signals:['onion','grapes','orange','jaggery'],risk:['spoilage','buyer concentration','fuel cost'],support:['PMEGP'],description:'Collect and move local produce to nearby shops or buyers.',descriptionMr:'स्थानिक उत्पादन गोळा करून जवळच्या दुकाने किंवा खरेदीदारांपर्यंत पोहोचवणे.',descriptionHi:'स्थानीय उत्पाद को पास के दुकानों या खरीदारों तक पहुँचाना।'}),
 b({id:'tailoring',line:'craft',name:'Tailoring & alterations',nameMr:'शिवणकाम व अल्टरशन',nameHi:'सिलाई और अल्टरेशन',cost:90000,working:20000,sales:40000,opex:18000,skills:['tailoring'],resources:['sewing_machine','workspace','cutting_table'],signals:['services'],risk:['customer acquisition','seasonality'],support:['PMEGP'],description:'Home or shop-based tailoring with low initial setup.',descriptionMr:'कमी प्रारंभिक खर्चात घरून किंवा दुकानातून शिवणकाम.',descriptionHi:'कम शुरुआती लागत में घर या दुकान से सिलाई।'}),
 b({id:'garments',line:'craft',name:'Small garment making',nameMr:'लहान गारमेंट उत्पादन',nameHi:'छोटा गारमेंट निर्माण',cost:190000,working:45000,sales:70000,opex:50000,skills:['tailoring'],resources:['sewing_machine','workspace','cutting_table','packaging'],signals:['services','retail'],risk:['quality','orders','fabric prices'],support:['PMEGP'],description:'Make simple garments for local shops or direct customers.',descriptionMr:'स्थानिक दुकाने किंवा ग्राहकांसाठी साधे कपडे तयार करणे.',descriptionHi:'स्थानीय दुकानों या ग्राहकों के लिए साधारण कपड़े बनाना।'}),
 b({id:'local_craft',line:'craft',name:'Local craft products',nameMr:'स्थानिक हस्तकला उत्पादने',nameHi:'स्थानीय हस्तशिल्प उत्पाद',cost:110000,working:25000,sales:45000,opex:26000,skills:['craft'],resources:['workspace','tools','storage'],signals:['retail','services'],risk:['demand','quality','market access'],support:['PMEGP'],description:'Produce locally distinctive craft or utility items.',descriptionMr:'स्थानिक वैशिष्ट्य असलेली हस्तकला किंवा उपयोगी उत्पादने तयार करणे.',descriptionHi:'स्थानीय पहचान वाले शिल्प या उपयोगी उत्पाद बनाना।'}),
 b({id:'two_wheeler',line:'service',name:'Two-wheeler repair',nameMr:'दुचाकी दुरुस्ती',nameHi:'दो-पहिया रिपेयर',cost:220000,working:40000,sales:85000,opex:58000,skills:['mechanical'],resources:['workshop','tools','spare_parts','technical_skill'],signals:['services'],risk:['skill quality','spares','competition'],support:['PMEGP'],description:'Repair and maintain two-wheelers for nearby customers.',descriptionMr:'जवळच्या ग्राहकांसाठी दुचाकी दुरुस्ती व देखभाल.',descriptionHi:'पास के ग्राहकों के लिए दोपहिया रिपेयर और मेंटेनेंस।'}),
 b({id:'electrical',line:'service',name:'Electrical repair',nameMr:'इलेक्ट्रिकल दुरुस्ती',nameHi:'इलेक्ट्रिकल रिपेयर',cost:100000,working:20000,sales:50000,opex:27000,skills:['electrical'],resources:['tools','technical_skill','workspace'],signals:['services'],risk:['safety','skill quality','demand'],support:['PMEGP'],description:'Household and small-shop electrical repair services.',descriptionMr:'घरगुती व छोट्या दुकानांसाठी इलेक्ट्रिकल दुरुस्ती सेवा.',descriptionHi:'घरों और छोटी दुकानों के लिए इलेक्ट्रिकल रिपेयर सेवा।'}),
 b({id:'mobile_repair',line:'service',name:'Mobile & electronics repair',nameMr:'मोबाईल व इलेक्ट्रॉनिक्स दुरुस्ती',nameHi:'मोबाइल और इलेक्ट्रॉनिक्स रिपेयर',cost:130000,working:25000,sales:60000,opex:34000,skills:['electronics'],resources:['tools','technical_skill','shop_space'],signals:['services','retail'],risk:['skill quality','parts','warranty issues'],support:['PMEGP'],description:'Repair common phones and small electronics locally.',descriptionMr:'सामान्य मोबाईल व छोट्या इलेक्ट्रॉनिक्सची स्थानिक दुरुस्ती.',descriptionHi:'सामान्य मोबाइल और छोटे इलेक्ट्रॉनिक्स की स्थानीय मरम्मत।'}),
 b({id:'catering',line:'service',name:'Small catering / food service',nameMr:'लहान केटरिंग / खाद्यसेवा',nameHi:'छोटा कैटरिंग / फूड सर्विस',cost:160000,working:40000,sales:75000,opex:52000,skills:['cooking'],resources:['kitchen','cooking_equipment','water','food_safety'],signals:['food','services'],risk:['orders','food safety','wastage'],support:['PMEGP'],description:'Provide small-event and local food catering with controlled menus and pre-orders.',descriptionMr:'लहान कार्यक्रम आणि स्थानिक ग्राहकांसाठी मर्यादित मेनूसह केटरिंग व खाद्यसेवा.',descriptionHi:'छोटे कार्यक्रम और स्थानीय ग्राहकों के लिए सीमित मेन्यू के साथ कैटरिंग और फूड सर्विस.'})
];
export const RESOURCES={en:[['water','Water'],['shed','Shed / suitable space'],['feed','Feed access'],['animals','Animals / birds'],['electricity','Electricity'],['workspace','Workspace'],['storage','Storage'],['kitchen','Kitchen'],['processing_equipment','Processing equipment'],['packaging','Packaging setup'],['food_safety','Food-safety knowledge'],['shop_space','Shop / service space'],['tools','Tools'],['technical_skill','Relevant technical skill'],['sewing_machine','Sewing machine'],['cutting_table','Cutting table'],['inventory_capital','Inventory capital'],['supplier_linkage','Supplier connection'],['transport','Transport'],['market_linkage','Buyer / market connection'],['bee_boxes','Bee boxes'],['protective_gear','Protective gear'],['flowering_area','Access to flowering areas'],['goats','Goats'],['fodder','Fodder access'],['vet_access','Veterinary access'],['spare_parts','Spare-parts access'],['grinding_setup','Grinding setup'],['workshop','Workshop'],['cooking_equipment','Cooking equipment']],mr:[['water','पाणी'],['shed','गोठा / योग्य जागा'],['feed','चारा उपलब्धता'],['animals','जनावरे / पक्षी'],['electricity','वीज'],['workspace','कामाची जागा'],['storage','साठवण जागा'],['kitchen','स्वयंपाकघर'],['processing_equipment','प्रक्रिया उपकरणे'],['packaging','पॅकेजिंग व्यवस्था'],['food_safety','अन्नसुरक्षा ज्ञान'],['shop_space','दुकान / सेवा जागा'],['tools','साधने'],['technical_skill','तांत्रिक कौशल्य'],['sewing_machine','शिवणयंत्र'],['cutting_table','कटिंग टेबल'],['inventory_capital','मालासाठी भांडवल'],['supplier_linkage','पुरवठादार संपर्क'],['transport','वाहतूक'],['market_linkage','खरेदीदार / बाजार संपर्क'],['bee_boxes','मधपेट्या'],['protective_gear','संरक्षण साधने'],['flowering_area','फुलोरा असलेल्या भागाची उपलब्धता'],['goats','शेळ्या'],['fodder','चारा'],['vet_access','पशुवैद्यकीय सुविधा'],['spare_parts','स्पेअर पार्ट्स संपर्क'],['grinding_setup','दळण व्यवस्था'],['workshop','वर्कशॉप'],['cooking_equipment','स्वयंपाकाची उपकरणे']],hi:[['water','पानी'],['shed','शेड / उपयुक्त जगह'],['feed','चारे की उपलब्धता'],['animals','पशु / पक्षी'],['electricity','बिजली'],['workspace','काम की जगह'],['storage','भंडारण'],['kitchen','रसोई'],['processing_equipment','प्रसंस्करण उपकरण'],['packaging','पैकेजिंग व्यवस्था'],['food_safety','खाद्य-सुरक्षा ज्ञान'],['shop_space','दुकान / सर्विस जगह'],['tools','औज़ार'],['technical_skill','तकनीकी कौशल'],['sewing_machine','सिलाई मशीन'],['cutting_table','कटिंग टेबल'],['inventory_capital','स्टॉक के लिए पूंजी'],['supplier_linkage','सप्लायर संपर्क'],['transport','परिवहन'],['market_linkage','खरीदार / बाजार संपर्क'],['bee_boxes','मधुमक्खी बक्से'],['protective_gear','सुरक्षा उपकरण'],['flowering_area','फूल वाले क्षेत्र तक पहुँच'],['goats','बकरियाँ'],['fodder','चारा'],['vet_access','पशु चिकित्सा सुविधा'],['spare_parts','स्पेयर पार्ट्स संपर्क'],['grinding_setup','पिसाई व्यवस्था'],['workshop','वर्कशॉप'],['cooking_equipment','खाना पकाने के उपकरण']]};
export const TALUKA_VILLAGES:Record<string,string[]>=Object.fromEntries(LOCATIONS.map(x=>[x.talukas[0],['Main village','Nearby village','Other village']]));
export const SCHEMES=[{id:'pmfme',name:'PMFME',scope:'Food processing / value addition',support:'Potentially relevant for eligible food-processing cases; current rules and implementing authority must be checked.',url:'https://pmfme.mofpi.gov.in/'},{id:'pmegp',name:'PMEGP',scope:'New micro-enterprises subject to scheme conditions',support:'Potentially relevant for eligible new micro-enterprises; project and activity rules must be checked.',url:'https://www.kviconline.gov.in/pmegpeportal/pmegphome/index.jsp'}];
